config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks"}

  root      "links#index"
  
  resources :links do
  	member do
  		put "like" , to: "links#upvote"
  		put "dislike" , to: "links#downvote"
  	end
  	resources :comments
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :link, dependent: :destroy

  validates :body, presence: true
end

app/models/link.rb
class Link < ActiveRecord::Base
	acts_as_votable
	belongs_to :user
	has_many :comments

	validates :title, presence: true
	validates :link, presence: true
	validates :description, presence: true

	def self.search(query)
	  where("link like ?", "%#{query}%") 
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :links
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2, :facebook]

   def self.from_omniauth(auth)
   	where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
   		user.provider 	= auth.provider
   		user.uid 	   	= auth.uid
   		user.email	   	= auth.info.email
             user.name         = auth.info.name
             user.image        = auth.info.image
   		user.password 	= Devise.friendly_token[0,20]
   	end
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :authenticate_user!
	def create
		@link = Link.find(params[:link_id])
		@comment = @link.comments.build comment_params
		@comment.user = current_user

		if @comment.save
			redirect_to :back
		else
			redirect_to :back 
		end
	end

	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy
		redirect_to :back
	end

	private

	def comment_params
		params.require(:comment).permit(:body)
	end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
	before_action :find_link, only: [ :update, :show, :edit, :destroy]
	before_filter :authenticate_user!, except: [:index, :show]
	def index	
		if params[:search]
			@links = Link.search(params[:search]).order("created_at DESC").paginate( page: params[:page], per_page: 3).order("created_at DESC")
		else
			@links = Link.all.paginate( page: params[:page], per_page: 3).order("created_at DESC")
		end
	end

	def new
		@link = current_user.links.build
	end

	def create
		@link = current_user.links.build link_params

		if @link.save
			redirect_to root_path, notice: "New link created"
		else
			render 'new'
		end
	end

	def show
	end

	def edit
	end

	def update
		if @link.update link_params
			redirect_to root_path, notice: 'Link updated'
		else
			render 'edit'
		end
	end

	def destroy
		@link.destroy
		redirect_to :back
	end

	def upvote
		@link = Link.find(params[:id])
		@link.upvote_by current_user
		redirect_to :back
	end

	def downvote
		@link = Link.find(params[:id])
		@link.downvote_by current_user
		redirect_to :back
	end

	private
	def link_params
		params.require(:link).permit(:title, :link, :description)
	end

	def find_link
		@link = Link.find(params[:id])
	end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def google_oauth2
		@user = User.from_omniauth(request.env["omniauth.auth"])
		sign_in_and_redirect @user
	end

	# if @user.persisted?
	# 	flash[:notice] = I18n.t("devise.omniauth_callbacks.success", kind: provider)
	# 	sign_in_and_redirect user, event: :authentication
	# else
	# 	session["devise.google_data"] = oauth_response.except(:extra)
	# 	params[:error] = :account_not_found
	# 	do_failure_things
	# end

	def facebook
		@user = User.from_omniauth(request.env["omniauth.auth"])
		sign_in_and_redirect @user
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/views/comments/_comment.html.erb
<div class="comment-content">
	<p><%= comment.body %></p>
	<p><small>Submited <%= time_ago_in_words(comment.created_at)  %>ago by <i><%= comment.user.name %></i></small></p>
	<div class="delete-comment">
		<% if user_signed_in? %>
			<% if comment.user == current_user %>
				<%= link_to "x", link_comment_path(@link, comment), method: :delete, data:{confirm: "Are you sure?"} %>
			<% end %>
		<% end %>
	</div>
</div>

app/views/layouts/_errors.html.erb
<% if @link.errors.any? %>
		<div id="errors">
			<h2>From contains <%= pluralize(@link.errors.count, "error") %>.</h2>
			<ul>
				<% @link.errors.full_messages .each do |msg|%>
				<li>
					<%= msg %>
				</li>
				<% end %>
			</ul>
		</div>
	<% end %>

app/views/layouts/_navigation.html.erb
<nav>
	<div class="nav-wrapper">
	  <%= link_to root_path, class: "brand-logo" do %>
	  	linker<span class='t'>T</span>hinker
	  <% end %>
	  <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
	  <ul class="right hide-on-med-and-down">
	  	<li><%= render "links/search_form" %></li>
	  	<% if user_signed_in? %>

		    	<li><%= link_to "Add Link", new_link_path, class:"waves-effect waves-light btn" %></li>
		    	<li class="navigation-avatar"><%= image_tag(current_user.image) if current_user.image%></li>
		    	<li><a class="dropdown-button" href="#!" data-activates="dropdown1">
			    	<% if !current_user.name.blank? %>
					<%= current_user.name %>
				<% else %>
					<%= current_user.email %>
				<% end %>
		    	<i class="material-icons right">arrow_drop_down</i></a></li>

			<ul id="dropdown1" class="dropdown-content">
			  <li><%= link_to "Account", edit_user_registration_path %></li>
			  <li class="divider"></li>
			  <li><%= link_to "Sign out", destroy_user_session_path, method: :delete  %></li>
			</ul>

		    	<% else %>
		    	<li><%= link_to "Sign up", new_user_registration_path, class:"" %></li>
		    	<li><%= link_to "Login", new_user_session_path, class:"" %></li>
	    	<% end %>
	   
	  </ul>
	  <ul class="side-nav" id="mobile-demo">
	    		<% if user_signed_in? %>
				<li class="navigation-avatar center"><%= image_tag(current_user.image) if current_user.image%></li>
				<li class="center">
					<% if !current_user.name.blank? %>
						<%= link_to current_user.name, edit_user_registration_path %>
					<% else %>
						<%= link_to current_user.email, edit_user_registration_path %>
					<% end %>
				</li>
				<li><%= link_to "Add Link", new_link_path, class:"waves-effect waves-light btn" %></li>
				<%= form_tag links_path, method: :get do %>
					<i class="material-icons search">search</i>
					<%= text_field_tag :search, params[:search], placeholder: "Search" %>	
				<% end %>
				<li class="mobile-signout center"><%= link_to "Sign out", destroy_user_session_path, method: :delete  %></li>
			<% else %>
				<li><%= link_to "Sign up", new_user_registration_path %></li>
				<li><%= link_to "Login", new_user_session_path %></li>
				<li class="mobile-search">
					<%= form_tag links_path, method: :get do %>
						<%= text_field_tag :search, params[:search], placeholder: "Search" %>	
					<% end %>
				</li>
			<% end %>
		</ul>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Linker-Thinker</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/navigation" %>
<div class="container">
	<div class="notification">
		<% if notice %>
			<p class="notice"><%= notice %></p>
		<% elsif alert %>
			<p class="alert"><%= alert %></p>
		<% end %>
	</div>
	

	<%= yield %>
</div>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/links/_form.html.erb
<%= simple_form_for @link do |f| %>
		
	<div class="input-field col s6">
		<%= f.input :title, id:"title", class:"" %>
	</div>
	<div class="input-field col s6">
		<%= f.input :link, id:"link", class:"" %>
	</div>
	<div class="input-field col s6">
		<%= f.input :description, id:"description", class:"" %>
	</div>

	<%= f.button :submit %>
	
<% end %>

app/views/links/_search_form.html.erb
<div class="search-form">
	<%= form_tag links_path, method: :get do %>
		<i class="material-icons search">search</i>
		<%= text_field_tag :search, params[:search], placeholder: "" %>	
	<% end %>
</div>

app/views/links/edit.html.erb
<%= render "form" %>

app/views/links/index.html.erb
<h3 class="index-title center">
    <i class="fa fa-link"></i> 
    Note your favourite links!
</h3>

<% if @links.present? %>
    <% @links.each do |link| %>

     <div class="card">
        <div class="card-content">
            <span class="card-title"><%= link.title %></span>
            <p>Created <%= time_ago_in_words(link.created_at) %> ago by <i>
            <% if link.user.name.blank? %>
                <%= link.user.email%></i></p>
            <% else %>
                <%= link.user.name %></i></p>
            <% end %>

            <span class="close">
                <% if user_signed_in? %>
                    <% if current_user.id == link.user_id %>
                        <%= link_to "x" , link_path(link), method: :delete, data:{confirm: "Are you sure?"} %>
                    <% end %>
                <% end %>
            </span>
        </div>
        <div class="card-action">
          <%= link_to "Show", link_path(link), class:"waves-effect waves-light btn" %>
          <% if user_signed_in? %>
            <% if current_user.id == link.user_id %>
                <%= link_to "Edit", edit_link_path(link), class:"waves-effect waves-light btn" %>
            <% end %>    
          <% end %>
        <span class="comment-count">
            <i class="material-icons">chat_bubble</i>
            <span><%= link.comments.count %></span>
        </span>
          
          <span class="vote">
                <%= link_to like_link_path(link), method: :put do %>
                    <i class="material-icons tiny">thumb_up</i>
                    <%= link.get_upvotes.size %>
                <% end %>
                <%= link_to dislike_link_path(link), method: :put do %>
                    <i class="material-icons tiny">thumb_down</i>
                    <%= link.get_downvotes.size %>
                <% end %>
            </span>
        </div>
      </div>

    <% end %>
<% else %>
    <p>There are no links containing the term(s) <b><i><%= params[:search] %>.</i></b></p>
    <%= link_to "Back to index", root_path, class:" btn waves-effect waves-light" %>
<% end %>

<ul class="pagination center">
    <li class="waves-effect"><%= will_paginate @links %></li>
</ul>


app/views/links/new.html.erb
<%= render "form" %>

app/views/links/show.html.erb
<h2><%= @link.title %></h2>
<p><%= @link.description %></p>

<%= link_to "Visit URL", @link.link, class:"waves-effect waves-light btn" %>

<span class="vote-show">
    <%= link_to like_link_path(@link), method: :put do %>
        <i class="material-icons tiny">thumb_up</i>
        <%= @link.get_upvotes.size %>
    <% end %>
    <%= link_to dislike_link_path(@link), method: :put do %>
        <i class="material-icons tiny">thumb_down</i>
        <%= @link.get_downvotes.size %>
    <% end %>
</span>

<br>
<h5 class="comment-header">Comments (<%= @link.comments.count %>)</h5>
<hr class="comment-divider">
<%= render @link.comments %>

<%= simple_form_for ([@link, @link.comments.build])  do |f| %>
	<%= f.text_area :body, id:"body", class:" input-field materialize-textarea", placeholder: "Leave comment" %>
	<%= f.button :submit %>
<% end %>